version: "3.9"

services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ewm_stats
    ports:
      - "6541:5432"
    command: ["postgres", "-c", "log_statement=all"]

  stats-server:
    build: ./stats/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/ewm_stats
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ewm_main
    ports:
      - "6542:5432"
    command: ["postgres", "-c", "log_statement=all"]

  ewm-service:
    build: ./main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm_main
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: password
      STATS_SERVICE_URL: http://stats-server:9090
      SPRING_JPA_HIBERNATE_DDL_AUTO: update